#!/usr/bin/python

import sys
import BulkUpload as BU

try:
    inventory_list = BU.parse(sys.argv[1])
except:
    msg = 'Encountered an error parsing workbook \'{0}\''.format(sys.argv[1])
    raise IOError(msg)

BU.authorization() # defaults to chrome
BU.upload(inventory_list) 
